require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.nnn"
require "user.autocommands"
require "user.comment"
require "user.toggleterm"

vim.cmd "colorscheme dracula"
